---
title: "Evaluation results Bern R Bootcamp FS 2019"
author: "MSM, DUW"
date: "2/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      error = FALSE)


library(googlesheets)
library(tidyverse)
library(kableExtra)

my_sheets <- gs_ls()
evaluation <- gs_title('February 2019 BernRBootcamp follow-up survey (Responses)') %>%
  gs_read(ws = 1)
```

## How satisfied were you with the bootcamp in general? (5 points scale, 5 = best)

```{r}
  evaluation %>%
  ggplot(aes(`How satisfied were you with the bootcamp in general?`)) +
    geom_histogram(binwidth = 0.5) +
    scale_x_continuous(limits = c(1, 5.5)) +
      scale_y_continuous(breaks = seq(0,10)) +
     geom_text(stat='count', aes(label=..count..), position = position_stack(vjust = 0.5),size=4) + 
    ylab('Count') + 
    theme_bw()
```


## Do you plan to rely on R in the future?

```{r}
  evaluation %>%
  ggplot(aes(`Do you plan to rely on R in the future?`)) +
    geom_histogram(binwidth = 0.5) +
    scale_x_continuous(limits = c(1, 5.5)) +
      scale_y_continuous(breaks = seq(0,10)) +
     geom_text(stat='count', aes(label=..count..), position = position_stack(vjust = 0.5),size=4) + 
    ylab('Count') + 
    theme_bw()
```


# Time allocation and difficulty (5 points scale, 3 = optimal)

```{r}
evaluation %>%
  select(`The amount of time allocated to presentations was`,
         `The amount of time allocated to practicals was`,
         `Generally the level of difficulty in the presentations was`,
         `Generally the level of difficulty in the practicals was`) %>%
  gather(question, value) %>%
  ggplot(aes(value)) +
  stat_count() + 
  facet_wrap(~ question, scales = "free") +
      scale_x_continuous(limits = c(1, 5.5)) +
  geom_text(stat='count', aes(label=..count..), position = position_stack(vjust = 0.5),size=4) +
  theme_bw() +
  xlab('Questions') + 
  ylab('Count')

```


## Do you have any other remarks regarding the workshop? How can we make the next workshop better?

```{r}
evaluation %>%
  select(`Do you have any other remarks regarding the workshop? How can we make the next workshop better?`) %>%
  table()

```
